[package]
name = "flint"
version = "0.1.0"
description = "An open-source, local-first Markdown knowledge base"
license = "AGPL-3.0-or-later"
repository = "https://github.com/cucsijuan/flint"
edition = "2024"
rust-version = "1.85"

[lib]
name = "flint_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
log = "0.4"
tauri = { version = "2.11.6", features = [] }
tauri-plugin-log = "2"
