[package]
name = "flint"
version = "0.1.0"
description = "An open-source, local-first Markdown knowledge base"
license = "AGPL-3.0-or-later"
repository = "https://github.com/cucsijuan/flint"
edition = "2024"
rust-version = "1.88"

[lib]
name = "flint_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
ignore = "0.4.33"
log = "0.4"
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
pulldown-cmark = { version = "0.13.4", default-features = false }
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
tauri = { version = "2.11.6", features = [] }
tauri-plugin-dialog = "2.7.3"
tauri-plugin-log = "2"
tauri-plugin-store = "2.4.5"
tauri-plugin-window-state = "2.4.1"
tempfile = "3.27.0"
thiserror = "2.0.21"
trash = "5.2.9"
yaml-rust2 = "0.13.0"
